### PR TITLE
conduit 1.1

### PR DESCRIPTION
**Pull request by snoyberg**

### CODE REVIEW

**Comment by snoyberg** [comment]
Would it be possible to get this onto Hackage?

**Comment by litherum** [comment]
@snoyberg I'm actually not super interested in maintaining this project any more. Do you know if there is a collection of these conduit packages I could add this to?

I'm happy with uploading this onto hackage today for the short-term, though.

**Comment by snoyberg** [comment]
It might be that someone is interesting in taking over maintainership, could you email the cafe and ask if anyone wants to take over? If no one steps up to the plate, let me know, and I'll include the code in the main conduit repo, at least temporarily.

If you add me as a maintainer on Hackage, I can also do these kinds of point releases.

**Comment by litherum** [comment]
I've added you as a maintainer. http://hackage.haskell.org/package/cereal-conduit/maintainers/

Thanks!

**Comment by litherum** [comment]
I've added you as a maintainer. http://hackage.haskell.org/package/cereal-conduit/maintainers/

Thanks!

**Comment by litherum** [comment]
Looks like no one is interested :(

**Comment by snoyberg** [comment]
OK, I've merged cereal-conduit into conduit, and updated the links in the cabal file to point to the new location.

**Pull request merged**
